[versions]
android-plugin = "8.7.3"
kotlin-plugin = "2.1.0"
track-plugin = "1.1.0"

androidx-junit = "1.2.1"
androidx-espresso = "3.6.1"
androidx-appcompat = "1.7.0"
androidx-activity = "1.9.3"
androidx-lifecycle-viewmodel = "2.8.7"
androidx-exifinterface = "1.3.7"
androidx-compose-bom = "2024.11.00"

junit = "4.13.2"
kotlinx-coroutines = "1.9.0"
leavesczy-matisse = "2.1.3"
tencent-imsdk = "8.3.6498"
coil = "3.0.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-plugin" }
leavesczy-track = { id = "io.github.leavesczy.track", version.ref = "track-plugin" }

chat-android-application = { id = "chat.android.application", version = "unspecified" }
chat-android-library = { id = "chat.android.library", version = "unspecified" }
chat-android-compose = { id = "chat.android.compose", version = "unspecified" }
chat-kotlin-parcelize = { id = "chat.kotlin.parcelize", version = "unspecified" }
chat-leavesczy-track = { id = "chat.leavesczy.track", version = "unspecified" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
leavesczy-track-gradle = { module = "io.github.leavesczy:track", version.ref = "track-plugin" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
leavesczy-matisse = { module = "io.github.leavesczy:matisse", version.ref = "leavesczy-matisse" }
tencent-imsdk = { module = "com.tencent.imsdk:imsdk-plus", version.ref = "tencent-imsdk" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }