name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - "**/WorkflowsTrigger.kt"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean with Gradle
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew app:assembleRelease

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          commit: master
          artifactErrorsFailBuild: true
          artifacts: "app/build/outputs/apk/release/*.apk"
          body: "create by workflows"
          token: ${{ secrets.ACTION_TOKEN }}
          tag: v0.0.${{ github.run_number }}
