name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - "**/WorkflowsTrigger.kt"

env:
  TZ: Asia/Shanghai

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk with Gradle
        run: ./gradlew app:assembleRelease

      - name: Get current time
        id: currentTime
        run: echo "time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"
          body: "create by workflows"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ steps.currentTime.outputs.time }}